data:
  # build: data
  image: znccompose_data
  volumes:
    - "/var/znc/.znc"

znc:
  build: .
  ports:
    - "6667:6667"
    - "6697:6697"
  volumes_from:
    - data
  restart: always
  # volumes:
  #   - "~/.znc:/var/znc/.znc"
